server:
  port: 8989
spring:
  application:
    name: GATEWAY-SERVICE

  cloud:
    gateway:
      routes:
        - id: ecom-product-service
          uri: lb://ECOM-PRODUCT-SERVICE
          predicates:
           - Path=/ecom/**
        - id: email-service
          uri: lb://EMAIL-SERVICE
          predicates:
           - Path=/api/**
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost
    